const BAD_REQUEST_STATUS_CODE = 400;

const UNAUTHORIZED_STATUS_CODE = 401;

const ASSERTION_ERROR_STATUS_CODE = 403;

const NOT_FOUND_STATUS_CODE = 404;

const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  UNAUTHORIZED_STATUS_CODE,
  ASSERTION_ERROR_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  INTERNAL_SERVER_ERROR,
};
